# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper.rb"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
end

require 'rubygems'
require 'test/unit'
require 'rspec'
require 'active_support/all'
require_relative '../Navigation'
require_relative '../Command'
require_relative '../Command_File'
require_relative '../My_Matrix'
require_relative '../Plateau'
require_relative '../Rover_Controller'
require_relative '../Rover'
require_relative '../Add_Ons'
require_relative '../Mars_Rover'
